### ISSUE TITLE
Requiring 'faunadb' from the package installed from npm fails

### ISSUE THREAD

**Issue by eaceaser** [faunadb/faunadb-js#75]
Depending on faunadb as such:

```
  "dependencies": {
    "faunadb": "git+ssh://git@github.com/faunadb/faunadb-js.git",
  }
```

then using it:

```
var faunadb = require('faunadb');
```

fails:

```
module.js:341
    throw err;
    ^

Error: Cannot find module './lib/model/Codec'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /home/eac/fauna/consulting/breezeworks/load/node_modules/faunadb/index.js:7:16
    at Array.forEach (native)
    at Object.<anonymous> (/home/eac/fauna/consulting/breezeworks/load/node_modules/faunadb/index.js:6:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

The relative paths here are problematic.

**Comment by eaceaser** [comment]
oh wait. this might be due to the fact that we require babel compilation.
